Testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,7 +28,64 @@ jobs:
       - name: Clean workspace
         run: Remove-Item -Recurse -Force *.* -ErrorAction Ignore
         shell: powershell
-      
+
+      - name: Choose Package
+        id: choose-package
+        run: |
+          $isPreconfigured = '${{ github.event.inputs.IS_PRECONFIGURED }}' -eq 'true'
+          $version = ''
+          $build = ''
+
+          if ($isPreconfigured) {
+              $version = '${{ github.event.inputs.BUILD_RELEASE }}'
+              $build = '${{ github.event.inputs.PACKAGE_NAME }}'
+          } else {
+              $relList = Get-ChildItem -Path ${{ env.DFS_UPGRADES_DIRECTORY }} | Sort-Object LastWriteTime -Descending | Select-Object -ExpandProperty Name
+              if ($relList.Count -gt 0) {
+                  $version = $relList[0]
+              } else {
+                  Write-Error "No releases found."
+                  exit 1
+              }
+          }
+
+          # Construct the path correctly
+          Remove-Item -Path "${{ env.DFS_UPGRADES_DIRECTORY }}\$version" -Recurse -Force -ErrorAction Ignore
+          New-Item -Path "${{ env.DFS_UPGRADES_DIRECTORY }}\$version\xstore-components-update-Ug31.0_Ug31.0_Ins31.0_x752_20241028-095120.jar" -ItemType Directory -Force
+          $packagePath = "${{ env.DFS_UPGRADES_DIRECTORY }}\$version"
+          Write-Host "Checking package path: $packagePath"
+
+          if (-not (Test-Path $packagePath)) {
+              Write-Error "Package path does not exist: $packagePath"
+              exit 1
+          }
+
+          $pckgList = Get-ChildItem -Path $packagePath -Filter *.jar | Sort-Object LastWriteTime -Descending | Select-Object -ExpandProperty Name
+          if (-not $pckgList) {
+              Write-Error "No package found in the specified directory."
+              exit 1
+          }
+
+          Write-Host "Version: $version"
+          Write-Host "Build: $build"
+
+          # Ensure that build is a valid .jar file
+          if (-not $build.EndsWith(".jar")) {
+              Write-Error "Error ... Incorrect selection."
+              exit 1
+          }
+
+          # Set environment variables for future steps
+          echo "version=$version" >> $GITHUB_ENV
+          echo "build=$build" >> $GITHUB_ENV
+
+        shell: powershell
+
+      - name: Print Version and Build (next step)
+        run: |
+          echo "Version: ${{ env.version }}"
+          echo "Build: ${{ env.build }}"
+
       - name: Choose Package
         id: choose-package
         run: |
@@ -76,7 +133,7 @@ jobs:
           
           echo "version=$version" >> $GITHUB_ENV
           echo "build=$build" >> $GITHUB_ENV
-          
+
           Write-Host "$env:version"
           Write-Host "${{ env.version }}"
           Write-Host "$env:build"
